export const SELECT_RESTOURANT = 'SELECT_RESTOURANT';
export const SELECT_MAP_CENTER = 'SELECT_MAP_CENTER';
export const SET_DATA = 'SET_DATA';
export const GET_SELECTED_RESTAURANTS = 'GET_SELECTED_RESTAURANTS';
export const SET_ROUT_PATH = 'SET_ROUT_PATH';
